### ISSUE TITLE
Add support to GNOME Shell 3.38

### ISSUE THREAD

**Issue by ranisalt** [gicmo/gamemode-extension#31]
I have installed it manually and it has been working great.

**Comment by laichiaheng** [comment]
2 months has passed.

**Comment by ranisalt** [comment]
Still working great.

**Comment by laichiaheng** [comment]
Still doesn't work via AUR.

**Comment by Redbatman89** [comment]
The extension is giving me errors in gnome logs

Object .Gjs_gamemode_christian_kellner_me_extension_GameModeIndicator (0x5565b80a8c60), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.

Object St.Icon (0x5565b7d04800), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.

**Comment by vanvugt** [comment]
@ranisalt, I'm confused. Are you saying 3.38 works or that it doesn't work? If the latter then it's [Ubuntu bug 1917098](https://bugs.launchpad.net/bugs/1917098).

Also, the issue mentioned above by @Redbatman89 is #35.

**Comment by ranisalt** [comment]
> @ranisalt, I'm confused. Are you saying 3.38 works or that it doesn't work?

*It's working great*. I mean no issues at all. Icon is there, turns green when activated and all.

**Comment by vanvugt** [comment]
> > @ranisalt, I'm confused. Are you saying 3.38 works or that it doesn't work?
> 
> _It's working great_. I mean no issues at all. Icon is there, turns green when activated and all.

Please close this issue then.

**Comment by ranisalt** [comment]
[No, it still does not mark 3.38 as supported](https://github.com/gicmo/gamemode-extension/blob/master/metadata.json.in)

**Comment by vanvugt** [comment]
Oh, right. In that case please clarify in the bug description that the problem is just `metadata.json.in`.

**Comment by gicmo** [comment]
3.38 should be supported in release 5. Thanks for your patience, sorry it took so long.
